### ISSUE TITLE
Wrong package number for Arch

### ISSUE THREAD

**Issue by pozar87** [walchko/pyarchey#8]
In pyarchey 0.6.2 there is small mistake in _Packages_ sub-class (pyarchay.py - line 475). The used dist name is _Arch_ instead of _Arch Linux_.

Correct line should be:

```
elif dist == 'Arch Linux':
```

Best Regards

**Comment by walchko** [comment]
making this and some other updates, thanks!

**Comment by walchko** [comment]
Does Arch have `/etc/os-release` file? If so, can you send me the contents of it?

**Comment by pozar87** [comment]
Hello,
Yes, it does:

```
 $ cat /etc/os-release 
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

Regards, 

PS Thanks for quick response :)

**Comment by walchko** [comment]
should be good now. I uploaded a new version to pypi
